---
abstract: 'modules I use'
author:
  - 'Jesse Luehrs <doy at tozt dot net>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-DOY
requires:
  App::Ack: 0
  App::ForkProve: v0.2.0
  App::Nopaste: 0.20
  App::Termcast: 0.06
  App::Ttyrec: 0
  App::cpanminus: 1.5007
  App::cpanoutdated: 0.05
  App::ph: 0
  App::pmuninstall: 0
  Archive::Zip: 0
  B::Keywords: 0
  Bread::Board::Declare: 0
  CPAN::Mini: 0
  Carp::Always::Color: 0.03
  Carp::REPL: 0
  Class::Refresh: 0
  DateTime: 0
  Devel::Cover: 0
  Devel::FindRef: 0
  Devel::NYTProf: 3.00
  Devel::PartialDump: 0
  Devel::REPL: 0
  Devel::STDERR::Indent: 0
  Devel::Trace: 0
  Dist::Zilla: 4.00
  Dist::Zilla::PluginBundle::DOY: 0.09
  ExtUtils::MakeMaker::Dist::Zilla::Develop: 0
  File::pushd: 0
  HTTP::Parser::XS: 0
  IO::Pty::Easy: 0.08
  JSON: 0
  LWP: 0
  LWP::Protocol::https: 0
  LastFM::Export: 0
  Moose: 2.0400
  Net::GitHub: 0.06
  Path::Class: 0.25
  Plack: 0
  Pod::Coverage::TrustPod: 0
  Pod::Cpandoc: 0
  Proc::InvokeEditor: 0
  Scalar::Defer: 0
  Term::ProgressBar: 0
  Term::ReadLine::Gnu: 0
  Term::TtyRec::Plus: 0.09
  Test::Fatal: 0
  Test::More: 0.88
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Pretty: 0
  Test::Requires: 0
  WWW::Mechanize: 0
  YAML: 0
  autodie: 0
  circular::require: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-DOY
  homepage: http://metacpan.org/release/Task-BeLike-DOY
  repository: git://github.com/doy/task-belike-doy.git
version: 0.07
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@DOY/TestMoreDoneTesting'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@DOY/GatherDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@DOY/PruneCruft'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@DOY/ManifestSkip'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@DOY/MetaYAML'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::License
      name: '@DOY/License'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@DOY/Readme'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@DOY/RunExtraTests'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@DOY/ExecDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@DOY/ShareDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@DOY/MakeMaker'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@DOY/Manifest'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@DOY/TestRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@DOY/ConfirmRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@DOY/MetaConfig'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@DOY/MetaJSON'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@DOY/NextRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@DOY/CheckChangesHasContent'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@DOY/PkgVersion'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@DOY/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@DOY/PodCoverageTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@DOY/PodSyntaxTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@DOY/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@DOY/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@DOY/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Metadata
      name: '@DOY/Metadata'
      version: 3.03
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@DOY/MetaResources'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@DOY/Git::Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@DOY/Git::Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@DOY/Git::Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@DOY/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@DOY/TaskWeaver'
      version: 0.101624
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@DOY/UploadToCPAN'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300020
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300020
x_authority: cpan:DOY
