---
abstract: 'modules I use'
author:
  - 'Jesse Luehrs <doy at tozt dot net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101151'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-DOY
recommends: {}
requires:
  App::Ack: 0
  App::Nopaste: 0.20
  App::Termcast: 0.06
  App::cpanminus: 1.00
  Archive::Zip: 0
  B::Keywords: 0
  CPAN::Mini: 0
  CPAN::Mini::Webserver: 0
  Carp::Always::Color: 0.03
  Carp::REPL: 0
  Devel::Cover: 0
  Devel::NYTProf: 3.00
  Devel::REPL: 0
  Dist::Zilla: 2.00
  IO::Pty::Easy: 0.08
  KiokuDB::Navigator: 0
  LWP: 0
  Module::Refresh: 0
  Module::Setup: 0
  Moose: 1.00
  Net::GitHub: 0.06
  Path::Class: 0
  Pod::Coverage::TrustPod: 0
  Scalar::Defer: 0
  Term::ReadLine::Gnu: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  WWW::Mechanize: 0
  YAML: 0
version: 0.01
